name: Update metadata files

on:
  # Run hourly
  schedule:
    - cron: "0 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/update.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # Let the default token commit and push.

jobs:
  sync:
    name: ðŸ”„ Sync metadata files
    runs-on: ubuntu-latest
    steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - name: ðŸ”„ Sync metadata files
        uses: snapcrafters/ci/sync-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          update-script: |
            make setup
            uv run ./tools/update.py
